-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 12:59:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materials` (
  `id` INT NOT NULL,
  `MATERIALS_NAME` INT NULL,
  `MATERIALS_QUANTITY` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventory` (
  `id` INT NOT NULL,
  `INVENTORY_NAME` VARCHAR(45) NULL,
  `INVENTORY_STORAGE` VARCHAR(45) NULL,
  `MATERIALS_NAME` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `MATERIALS_NAME_idx` (`MATERIALS_NAME` ASC) VISIBLE,
  CONSTRAINT `MATERIALS_NAME`
    FOREIGN KEY (`MATERIALS_NAME`)
    REFERENCES `mydb`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory_has_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventory_has_materials` (
  `inventory_id` INT NOT NULL,
  `materials_id` INT NOT NULL,
  PRIMARY KEY (`inventory_id`, `materials_id`),
  INDEX `fk_inventory_has_materials_materials1_idx` (`materials_id` ASC) VISIBLE,
  INDEX `fk_inventory_has_materials_inventory1_idx` (`inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_has_materials_inventory1`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `mydb`.`inventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_has_materials_materials1`
    FOREIGN KEY (`materials_id`)
    REFERENCES `mydb`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
